#!/usr/bin/bash

# store feehh
cd ../DATA_BASE_CREATED

while true
do 
#echo "please enter your database name"
#read name_db 
#hena  type --entry 3l4an ya5od input mn el user w y3melo store f name_db

name_db=$(zenity --entry --title="Create Database" --text="please enter your database name ")


# $?: This is a special variable in bash that always 
# contains the exit status of the most recently executed command. 



# kda check exit
if [ $? -eq 1 ]
then
   exit 0
fi

# matnse4 case can't start with speical character!!!(Done)
case $name_db in
 # is empty
 "" )
   # henna --error de to display eror msg
   zenity --error --text="database name can't be empty"
    echo "database name can't be empty"
   continue
   ;;

    #condition da m4 48al kways 8er f el nos bs!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!1
  *[[:space:]] | *[[:space:]]* | [[:space:]]*   )
     zenity --error --text="database name can't contain space"
     #echo "database name can't contain space"
    continue
   ;;
  [0-9]* )

  zenity --error --text="database name can't start with number"
  #echo "database name can't start with number"
  continue
   ;;
 [!a-zA-Z0-9_]*)
       zenity --error --text="database name can't contain special characters."
         echo "database name can't contain special characters."
         continue
         ;;    

   # 3ayza a5leha 2 cases speaical char w elba2y 
  *[a-zA-Z]*[a-zA-Z_0-9] | [a-zA-Z_]) 
      if  [ -e $name_db ]
      then 
         zenity --error --text="the database is already exist"
        # echo "the database is already exist"
         continue 
      else
    # momken 22ol do you want to  edit the exisiting db 
          mkdir $name_db 
          #de b display information msg box
          zenity --info --text="the database created sussecfully"

          break 
      fi
      ;;
   *)
    zenity --error --text="database name is invalid"
    # echo "database name is invalid"
     continue 
     ;; 
esac
done
cd - 2> /dev/null