#!/usr/bin/bash


echo  Please Choose the table  to delete from

array=( `ls` )

select choice in ${array[*]}
do 
   if [ $REPLY -gt ${#array[*]} ]
  then 
    echo $REPLY not in menue
    continue
   else
    table_name=${array[${REPLY}-1]} 2>/dev/null  # array start from 0 f lazem 3l4an my3ml4 delete lly ba3do 
     echo 'you are now inside '${array[${REPLY}-1]}' table' 

     break 
   fi
done


col_types=$(awk -F: '{print $2}' .$table_name"_metadata" 2> /dev/null)
col_names=$(awk -F: '{print $1}' .$table_name"_metadata" 2> /dev/null)
names=($col_names)
types=($col_types)


echo "Column Names: $col_names"
echo "Column Types: $col_types"
echo "Names Array: ${names[@]}"
echo "Types Array: ${types[@]}"
echo "Number of Names: ${#names[@]}"

row=()
#echo $row
num_lines=$(wc -l <  $table_name)  
#echo $num_lines
for ((i=1; i<=$num_lines; i++))
do
  row=$(sed -n "$i p" $table_name)
  rows+=("$row")
done




select de_choice in delete_all_table  delete_specific_column  delete_by_id  exit
do 
case $de_choice in
delete_all_table )
    #  -s option for size 0 =0 bytes
    truncate -s 0 $table_name 
    echo the table content deleted successfully
    ;;
delete_specific_column  )

          echo "Please choose the column to delete:"
    select col_delete in "${names[@]}"
    do
        if [ $REPLY -gt ${#names[@]} ]
        then
            echo "$REPLY not in menu"
            continue
        else
            col_index=$REPLY # index bta3 el col
            for ((i=1; i<=$num_lines; i++))
            do
                line=$(sed -n "$i p" $table_name)
                # Split the line into an array
                IFS=: read -r -a line_array <<< "$line"

                # Replace the column value with an empty string
                line_array[$col_index-1]=""
    
                # Join the array back into a line
                new_line=$(IFS=:; echo "${line_array[*]}")

                # Replace the original line with the new line
                sed -i "$i s/.*/$new_line/" $table_name
            done

            echo "Column $col_delete deleted successfully"
            break
        fi
    done
    
     ;;
delete_by_id)
    read -p "input the id of the row you want to delete : " id
    sed -i "/^$id/d" $table_name
    echo "the row with is $id deleted sussufully"
    ;;

exit )
    #feh error 3ayzeeen nhandeloooo 
    source ../../SW/connect_db   
    ;;      
esac
done