#!/usr/bin/bash

 cd ../DATA_BASE_CREATED


#  ls -F | grep / | tr / " "



echo "choose the database you want to drop"


array=(`ls -F | grep / | tr / " "`)



choice=$(zenity --list --title="Choose Database to Drop" --text="Select a database to drop:" --column="Databases" "${array[@]}")


if [ $? -eq 1 ]; then
  exit 0
fi




# de kant 48ala lma kan bya5od rakam
# select choice in ${array[*]}
# do 
#   if [ $REPLY -gt ${#array[*]} ]
#   then 

#     zenity --error --text="$REPLY not in menue"
#     echo $REPLY not in menue
#     continue
#    else
#      rm -r ${array[${REPLY}-1]} # array start from 0f lazem 3l4an my3ml4 delete lly ba3do 

     
#      echo the database is deleted successfully
#      break 

#    fi
# done     




if zenity --question --text="Are you sure you want to drop the database $choice?"
then
  rm -r "$choice"
  zenity --info --text="The database $choice has been dropped successfully."
  echo "The database is dropped successfully"
else
  zenity --info --text="Drop cancelled."
fi

 cd -  2> /dev/null
