#!/usr/bin/bash


echo ===============exsist tables===============

tables_list=$(ls)


zenity --list --title "List of Tables" --text "Select table:" --column "tables" --print-column=1   $tables_list
 
#case check i no tables if exsist may redirect to another place 

#   if (`ls` == null )
#      echo no tables to list 
#      continue
#   else
#     ls
#   fi     