#!/usr/bin/bash


#echo "----------list the existing database-----------------------"
 
cd ../DATA_BASE_CREATED

#store f el variable da 3l4an 22dr 23rado as list in one column 

database_list=$(ls -F | grep / | tr / " ")


    if [ $? -eq 1 ]
    then
        exit 0
    fi

#--column "Databases" --print-column=1   $database_list
# way tanya to list the bdl m a5thom gwa store f variable aw array el awel
#  echo "$database_list" | 
zenity --list --title "List DB" --text "Select a database:" --column "Databases" --print-column=1   $database_list
 
cd -  2> /dev/null
